services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: eventstore
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"